package vn.com.fis.consentcore.extension.api;

/** Stable lifecycle hooks exposed by Consent Core. Existing aliases are retained for compatibility. */
public enum ExtensionPoint {
    BEFORE_CONSENT_BUILD,
    AFTER_CONSENT_BUILD,
    BEFORE_CONSENT_REGISTRATION,
    AFTER_CONSENT_REGISTRATION,
    BEFORE_EXTERNAL_CONSENT_REGISTRATION,
    AFTER_EXTERNAL_CONSENT_REGISTRATION,
    BEFORE_CONTENT_REVISION,
    AFTER_CONTENT_REVISION,
    BEFORE_CONSENT_GRANT,
    AFTER_CONSENT_GRANTED,
    BEFORE_CONSENT_AUTHORIZATION,
    AFTER_CONSENT_AUTHORIZATION,
    BEFORE_EVIDENCE_ATTACHMENT,
    AFTER_EVIDENCE_ATTACHMENT,
    BEFORE_EVIDENCE_VERIFICATION,
    AFTER_EVIDENCE_VERIFIED,
    AFTER_EVIDENCE_REJECTED,
    AFTER_ARTIFACT_SUPERSEDED
}
