package vn.com.fis.consentcore.shared.error;

public enum ErrorCode {
    CONSENT_NOT_FOUND,
    CONSENT_ALREADY_EXISTS,
    CONSENT_INVALID_STATE_TRANSITION,
    CONSENT_EVIDENCE_NOT_VERIFIED,
    CONSENT_CONTENT_NOT_FINALIZED,
    CONSENT_DECISION_REQUIRED,
    CONSENT_NOT_YET_EXPIRED,
    CONSENT_VALIDITY_INVALID,
    CONSENT_AUTHORIZATION_BINDING_INVALID,
    CONSENT_DATA_REQUIREMENT_UNRESOLVED,
    CONSENT_DATA_PROVIDER_UNAVAILABLE,
    CONSENT_PREPARATION_SELECTION_INVALID,
    CONSENT_PREPARATION_STALE,
    IDEMPOTENCY_KEY_REUSED,
    VALIDATION_ERROR,
    NOT_FOUND,
    CONFLICT,
    INTERNAL_ERROR
}
