CREATE TABLE consent (
                         id                           RAW(16) PRIMARY KEY,
                         tenant_id                    VARCHAR2(100) NOT NULL,
                         external_request_id          VARCHAR2(200),
                         consent_type                 VARCHAR2(100) NOT NULL,
                         subject_id                   VARCHAR2(200),
                         client_id                    VARCHAR2(200) NOT NULL,
                         purpose                      VARCHAR2(500),
                         status                       VARCHAR2(60) NOT NULL,
                         valid_from                   TIMESTAMP WITH TIME ZONE NOT NULL,
                         valid_until                  TIMESTAMP WITH TIME ZONE NOT NULL,
                         acquisition_channel          VARCHAR2(60) NOT NULL,
                         capture_method               VARCHAR2(60) NOT NULL,
                         source_system                VARCHAR2(100) NOT NULL,
                         external_consent_id          VARCHAR2(200),
                         evidence_policy              VARCHAR2(40) NOT NULL,
                         evidence_status              VARCHAR2(40) NOT NULL,
                         trusted_source_authorization NUMBER(1) DEFAULT 0 NOT NULL,
                         authorization_reference      VARCHAR2(300),
                         created_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
                         updated_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
                         created_by                   VARCHAR2(200) NOT NULL,
                         updated_by                   VARCHAR2(200) NOT NULL,
                         version                      NUMBER(19) DEFAULT 0 NOT NULL,
                         CONSTRAINT ck_consent_status CHECK ( status IN ( 'REGISTERED', 'AWAITING_AUTHORIZATION', 'AUTHORIZED', 'REJECTED', 'SUSPENDED',
                                                                          'REVOKED', 'EXPIRED', 'CANCELLED' ) ),
                         CONSTRAINT ck_consent_evidence_policy CHECK ( evidence_policy IN ( 'REQUIRED', 'NOT_REQUIRED' ) ),
                         CONSTRAINT ck_consent_evidence_status CHECK ( evidence_status IN ( 'NOT_REQUIRED', 'PENDING', 'VERIFIED', 'REJECTED', 'SUPERSEDED'
                             ,
                                                                                            'EXPIRED' ) ),
                         CONSTRAINT ck_consent_validity CHECK ( valid_until > valid_from ),
                         CONSTRAINT ck_consent_trusted_auth CHECK ( trusted_source_authorization IN ( 0, 1 ) ),
                         CONSTRAINT ck_consent_trusted_evidence CHECK ( trusted_source_authorization = 0
                             OR evidence_policy = 'NOT_REQUIRED' ),
                         CONSTRAINT ck_consent_authorized_ref CHECK ( status <> 'AUTHORIZED'
                             OR authorization_reference IS NOT NULL )
);

CREATE UNIQUE INDEX uk_consent_external_source ON
    consent (
             CASE
                 WHEN
                external_consent_id
            IS NOT NULL THEN
                    tenant_id
        END,
             CASE
                 WHEN
                external_consent_id
            IS NOT NULL THEN
                    source_system
        END,
             external_consent_id
        );

CREATE INDEX ix_consent_tenant_status ON
    consent (
             tenant_id,
             status,
             updated_at
             DESC );

CREATE INDEX ix_consent_tenant_subject ON
    consent (
             tenant_id,
             subject_id,
             created_at
             DESC );

CREATE INDEX ix_consent_tenant_client ON
    consent (
             tenant_id,
             client_id,
             created_at
             DESC );

CREATE INDEX ix_consent_expiry_candidate ON
    consent (
             CASE
                 WHEN
                status
            IN ( 'REGISTERED', 'AWAITING_AUTHORIZATION', 'AUTHORIZED', 'SUSPENDED' ) THEN
                    tenant_id
        END,
             CASE
                 WHEN
                status
            IN ( 'REGISTERED', 'AWAITING_AUTHORIZATION', 'AUTHORIZED', 'SUSPENDED' ) THEN
                    valid_until
        END
        );

CREATE TABLE consent_status_history (
                                        id             RAW(16) PRIMARY KEY,
                                        sequence_no    NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
    UNIQUE,
                                        consent_id     RAW(16) NOT NULL,
                                        tenant_id      VARCHAR2(100) NOT NULL,
                                        from_status    VARCHAR2(60),
                                        to_status      VARCHAR2(60) NOT NULL,
                                        reason_code    VARCHAR2(100) NOT NULL,
                                        reason_detail  VARCHAR2(1000),
                                        actor_id       VARCHAR2(200) NOT NULL,
                                        actor_type     VARCHAR2(40) NOT NULL,
                                        source_system  VARCHAR2(100) NOT NULL,
                                        correlation_id VARCHAR2(100) NOT NULL,
                                        request_id     VARCHAR2(100) NOT NULL,
                                        occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
                                        CONSTRAINT fk_consent_hist_consent FOREIGN KEY ( consent_id )
                                            REFERENCES consent ( id ),
                                        CONSTRAINT ck_history_from_status CHECK ( from_status IS NULL
                                            OR from_status IN ( 'REGISTERED', 'AWAITING_AUTHORIZATION', 'AUTHORIZED', 'REJECTED', 'SUSPENDED'
                                                ,
                                                                'REVOKED', 'EXPIRED', 'CANCELLED' ) ),
                                        CONSTRAINT ck_history_to_status CHECK ( to_status IN ( 'REGISTERED', 'AWAITING_AUTHORIZATION', 'AUTHORIZED', 'REJECTED', 'SUSPENDED'
                                            ,
                                                                                               'REVOKED', 'EXPIRED', 'CANCELLED' ) ),
                                        CONSTRAINT ck_history_actor_type CHECK ( actor_type IN ( 'USER', 'SERVICE', 'SYSTEM' ) )
);

CREATE INDEX ix_consent_hist_tenant_seq ON
    consent_status_history (
                            tenant_id,
                            consent_id,
                            sequence_no
        );

CREATE TABLE consent_idempotency (
                                     id              RAW(16) PRIMARY KEY,
                                     tenant_id       VARCHAR2(100) NOT NULL,
                                     idempotency_key VARCHAR2(200) NOT NULL,
                                     operation       VARCHAR2(100) NOT NULL,
                                     request_hash    VARCHAR2(64) NOT NULL,
                                     consent_id      RAW(16) NOT NULL,
                                     created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
                                     expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
                                     CONSTRAINT fk_consent_idemp_consent FOREIGN KEY ( consent_id )
                                         REFERENCES consent ( id ),
                                     CONSTRAINT uk_consent_idempotency UNIQUE ( tenant_id,
                                                                                idempotency_key,
                                                                                operation ),
                                     CONSTRAINT ck_consent_idemp_expiry CHECK ( expires_at > created_at )
);

CREATE INDEX ix_consent_idempotency_expiry ON
    consent_idempotency (
                         expires_at
        );

CREATE TABLE audit_event (
                             id             RAW(16) PRIMARY KEY,
                             tenant_id      VARCHAR2(100) NOT NULL,
                             aggregate_type VARCHAR2(100) NOT NULL,
                             aggregate_id   RAW(16) NOT NULL,
                             action         VARCHAR2(100) NOT NULL,
                             result         VARCHAR2(40) NOT NULL,
                             actor_id       VARCHAR2(200) NOT NULL,
                             actor_type     VARCHAR2(40) NOT NULL,
                             source_system  VARCHAR2(100) NOT NULL,
                             correlation_id VARCHAR2(100) NOT NULL,
                             request_id     VARCHAR2(100) NOT NULL,
                             details        CLOB DEFAULT '{}' NOT NULL,
                             occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
                             CONSTRAINT ck_audit_actor_type CHECK ( actor_type IN ( 'USER', 'SERVICE', 'SYSTEM' ) ),
                             CONSTRAINT ck_audit_result CHECK ( result IN ( 'SUCCESS', 'FAILURE' ) ),
                             CONSTRAINT ck_audit_details_json CHECK ( details IS JSON )
);

CREATE INDEX ix_audit_tenant_agg_time ON
    audit_event (
                 tenant_id,
                 aggregate_type,
                 aggregate_id,
                 occurred_at
                 DESC );

CREATE INDEX ix_audit_correlation ON
    audit_event (
                 tenant_id,
                 correlation_id,
                 occurred_at
                 DESC );

CREATE TABLE outbox_event (
                              id             RAW(16) PRIMARY KEY,
                              sequence_no    NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
    UNIQUE,
                              tenant_id      VARCHAR2(100) NOT NULL,
                              aggregate_type VARCHAR2(100) NOT NULL,
                              aggregate_id   RAW(16) NOT NULL,
                              event_type     VARCHAR2(200) NOT NULL,
                              event_version  NUMBER(10) NOT NULL,
                              payload        CLOB NOT NULL,
                              correlation_id VARCHAR2(100) NOT NULL,
                              occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
                              status         VARCHAR2(20) NOT NULL,
                              attempts       NUMBER(10) DEFAULT 0 NOT NULL,
                              available_at   TIMESTAMP WITH TIME ZONE NOT NULL,
                              locked_by      VARCHAR2(200),
                              locked_at      TIMESTAMP WITH TIME ZONE,
                              published_at   TIMESTAMP WITH TIME ZONE,
                              last_error     VARCHAR2(2000),
                              created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
                              CONSTRAINT ck_outbox_status CHECK ( status IN ( 'PENDING', 'PROCESSING', 'PUBLISHED', 'DEAD' ) ),
                              CONSTRAINT ck_outbox_attempts CHECK ( attempts >= 0 ),
                              CONSTRAINT ck_outbox_event_version CHECK ( event_version > 0 ),
                              CONSTRAINT ck_outbox_payload_json CHECK ( payload IS JSON )
);

CREATE INDEX ix_outbox_pending ON
    outbox_event (
                  CASE
                      WHEN
                status
            IN ( 'PENDING', 'PROCESSING' ) THEN
                    status
        END,
                  CASE
                      WHEN
                status
            IN ( 'PENDING', 'PROCESSING' ) THEN
                    available_at
        END,
                  CASE
                      WHEN
                status
            IN ( 'PENDING', 'PROCESSING' ) THEN
                    sequence_no
        END
        );

CREATE INDEX ix_outbox_aggregate ON
    outbox_event (
                  tenant_id,
                  aggregate_type,
                  aggregate_id,
                  occurred_at
        );

COMMENT ON TABLE consent IS
    'Current state of the Consent aggregate. Tenant-scoped queries are mandatory.';

COMMENT ON TABLE consent_status_history IS
    'Append-only lifecycle transition history written in the same transaction as consent.';

COMMENT ON TABLE consent_idempotency IS
    'Idempotency result index for externally retried consent commands.';

COMMENT ON TABLE audit_event IS
    'Append-only business audit trail. Sensitive evidence content must not be stored here.';

COMMENT ON TABLE outbox_event IS
    'Custom transactional outbox per OPEN-DB-05.';